version: '3.8'

services:
  backend:
    build: ./backend
    container_name: yt-analyzer-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - appnet
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: yt-analyzer-frontend
    environment:
      - VITE_API_BASE=http://backend:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge


